# Generated by Django 5.2 on 2025-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsmodel',
            name='refresh_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
