# Generated by Django 5.2 on 2025-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationsmodel_refresh_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsmodel',
            name='platform',
            field=models.CharField(choices=[('X', 'X'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook')], max_length=1000),
        ),
    ]
